// Code generated by "command/cmd/gen". DO NOT EDIT.

package command

const topLevelHelp = `Usage: ratchet COMMAND

  pin       Resolve and pin all versions
  unpin     Revert pinned versions to their unpinned values
  update    Update all pinned versions to the latest value
`
