// Code generated by "command/cmd/gen". DO NOT EDIT.

package command

const topLevelHelp = `Usage: ratchet COMMAND

  check     Check if all versions are pinned
  pin       Resolve and pin all versions
  unpin     Revert pinned versions to their unpinned values
  update    Update all pinned versions to the latest value

Available parsers:

  actions
  circleci
  cloudbuild
  drone
  gitlabci
`
