name: 'release'

on:
  push:
    tags:
      - 'v*'

permissions:
  attestations: 'write'
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130' # ratchet:docker/setup-qemu-action@v3

      - uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # ratchet:actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: 'actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5' # ratchet:actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - uses: 'docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9' # ratchet:docker/login-action@v3
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - uses: 'goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a' # ratchet:goreleaser/goreleaser-action@v6
        id: 'goreleaser'
        with:
          version: '~> 2'
          args: 'release --clean --fail-fast'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: 'actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a' # ratchet:actions/attest-build-provenance@v3
        with:
          subject-path: |-
            dist/*.tar.gz
            dist/*.zip
