name: 'test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: 'read'
  statuses: 'write'

jobs:
  lint:
    strategy:
      matrix:
        os:
          - 'macos-latest'
          - 'ubuntu-latest'
      fail-fast: false
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0' # ratchet:actions/checkout@v7

      - uses: './'
        with:
          files: '.github/workflows/*.yml'

  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0' # ratchet:actions/checkout@v7

      - uses: 'actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e' # ratchet:actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: 'Run tests'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        run: |-
          go test \
            -count=1 \
            -shuffle=on \
            -timeout=10m \
            -race \
            ./...
