name: 'test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        os:
          - 'macos-latest'
          - 'ubuntu-latest'
      fail-fast: false
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - uses: './'
        with:
          files: '.github/workflows/*.yml'

  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - uses: 'actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b' # ratchet:actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: 'Run tests'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        run: |-
          go test \
            -count=1 \
            -shuffle=on \
            -timeout=10m \
            -race \
            ./...
