name: 'test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: 'read'
  statuses: 'write'

jobs:
  lint:
    strategy:
      matrix:
        os:
          - 'macos-latest'
          - 'ubuntu-latest'
      fail-fast: false
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # ratchet:actions/checkout@v6

      - uses: './'
        with:
          files: '.github/workflows/*.yml'

  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # ratchet:actions/checkout@v6

      - uses: 'actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5' # ratchet:actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: 'Run tests'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        run: |-
          go test \
            -count=1 \
            -shuffle=on \
            -timeout=10m \
            -race \
            ./...
